# Generated by Django 4.0.6 on 2022-10-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CD_MUN', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('NM_MUN', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('SIGLA_UF', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('AREA_KM2', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
