# Generated by Django 4.0.6 on 2023-03-30 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_setor', models.CharField(max_length=15)),
                ('cd_sit', models.CharField(max_length=1)),
                ('nm_sit', models.CharField(max_length=50)),
                ('cd_uf', models.CharField(max_length=2)),
                ('nm_uf', models.CharField(max_length=50)),
                ('sigla_uf', models.CharField(max_length=2)),
                ('cd_mun', models.CharField(max_length=7)),
                ('nm_mun', models.CharField(max_length=60)),
                ('cd_dist', models.CharField(max_length=9)),
                ('nm_dist', models.CharField(max_length=100)),
                ('cd_subdist', models.CharField(max_length=11)),
                ('nm_subdist', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, srid=4326)),
            ],
        ),
    ]
