# Generated by Django 4.0.6 on 2023-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectors',
            name='cd_dist',
            field=models.CharField(blank=True, default=None, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='cd_mun',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='cd_sit',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='cd_subdist',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='cd_uf',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='nm_dist',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='nm_mun',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='nm_sit',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='nm_subdist',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='nm_uf',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='sigla_uf',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
