# Generated by Django 4.0.6 on 2023-04-15 01:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_alter_sectors_cd_dist_alter_sectors_cd_mun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorsSensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_setor', models.CharField(max_length=255)),
                ('cd_sit', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nm_sit', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cd_uf', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nm_uf', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sigla_uf', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cd_mun', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nm_mun', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cd_dist', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nm_dist', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cd_subdist', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nm_subdist', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, srid=4326)),
            ],
        ),
    ]
