# Generated by Django 4.0.6 on 2023-04-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0005_rename_cd_dist_sectorssensus_cd_geocodb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorssensus',
            name='geo_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
