# Generated by Django 4.0.6 on 2022-10-19 21:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district_property', '0001_add_district_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(default='district', max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(default='Feature', max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, srid=4326)),
                ('properties', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='district_property.districtproperty')),
            ],
        ),
    ]
