# Generated by Django 4.0.6 on 2023-03-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        ('dictionary', '0006_alter_dictionary_format_alter_dictionary_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to='dictionary.dictionary')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='state.state')),
            ],
        ),
    ]
