# Generated by Django 4.0.6 on 2023-03-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
        ('dictionary', '0006_alter_dictionary_format_alter_dictionary_unit'),
        ('district', '0001_initial'),
        ('data', '0002_data_state_spreadsheet_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Spreadsheet_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.spreadsheet_register')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='district.district')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_city', to='dictionary.dictionary')),
            ],
        ),
    ]
