# Generated by Django 4.0.6 on 2023-04-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_dictionary_ranking'),
        ('upload', '0001_initial'),
        ('sectors', '0002_alter_sectors_cd_dist_alter_sectors_cd_mun_and_more'),
        ('data', '0003_data_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Spreadsheet_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.spreadsheet_register')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_sector', to='dictionary.dictionary')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='sectors.sectors')),
            ],
        ),
    ]
