# Generated by Django 4.0.6 on 2023-04-15 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0004_sectorssensus'),
        ('data', '0004_data_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_sector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='sectors.sectorssensus'),
        ),
    ]
