# Generated by Django 4.0.6 on 2023-09-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_data_sector_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnae', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1000)),
                ('cod_setor', models.CharField(max_length=255)),
                ('nome_setor', models.CharField(max_length=1000)),
            ],
        ),
    ]
