# Generated by Django 4.0.6 on 2023-09-14 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
        ('district', '0004_delete_cnae_city'),
        ('data', '0008_alter_cnae_cnae_alter_cnae_cod_setor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnae_munic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('Spreadsheet_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.spreadsheet_register')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='munic', to='district.district')),
                ('cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnae_cod', to='data.cnae')),
            ],
        ),
    ]
