# Generated by Django 4.0.6 on 2022-10-20 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to='dictionary.dictionary')),
            ],
        ),
    ]
