# Generated by Django 4.0.6 on 2022-10-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.CharField(choices=[('state', 'State'), ('district', 'District')], default='state', max_length=50),
        ),
    ]
