# Generated by Django 4.0.6 on 2023-03-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='Unit',
            new_name='unit',
        ),
    ]
