# Generated by Django 4.0.6 on 2023-03-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rename_unit_dictionary_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='comments_en',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
