# Generated by Django 4.0.6 on 2023-03-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_dictionary_comments_ptbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='table',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
