# Generated by Django 4.0.6 on 2023-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_dictionary_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='format',
            field=models.CharField(blank=True, default='Int', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
