# Generated by Django 4.0.6 on 2023-04-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_remove_dictionary_comments_ptbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='comments_en',
        ),
    ]
