# Generated by Django 4.0.6 on 2022-10-20 06:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='state', max_length=255)),
                ('type', models.CharField(default='Feature', max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, srid=4326)),
                ('CD_UF', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('POPULATION', models.IntegerField(blank=True, default=None, null=True)),
                ('NM_UF', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('SIGLA_UF', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('NM_REGIAO', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
