# Generated by Django 4.0.6 on 2022-10-18 20:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, srid=4326),
        ),
    ]
