# Generated by Django 4.0.6 on 2022-10-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_state_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='type',
            field=models.CharField(default='Feature', max_length=255),
        ),
    ]
