# Generated by Django 4.0.6 on 2023-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='POPULATION',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
