# Generated by Django 4.0.6 on 2023-09-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_cnae_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cnae_city',
        ),
    ]
