# Generated by Django 4.0.6 on 2022-10-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('name', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('agency', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('format', models.CharField(choices=[('INT', 'Int'), ('FLOAT2', 'Float2')], default='INT', max_length=255)),
                ('classification', models.CharField(choices=[('Econômica', 'Economy'), ('Demográfica', 'Demographic')], default='Econômica', max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('label', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('unit', models.CharField(choices=[('Money', 'Money'), ('Number', 'Number'), ('Distance', 'Distance')], default='Number', max_length=255)),
            ],
        ),
    ]
