# Generated by Django 4.0.6 on 2022-10-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='classification',
            field=models.CharField(choices=[('E', 'Econômica'), ('D', 'Demográfica')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='format',
            field=models.CharField(choices=[('INT', 'INT'), ('FT2', 'FLOAT2')], default='INT', max_length=3),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='unit',
            field=models.CharField(choices=[('M', 'Money'), ('N', 'Number'), ('D', 'Distance')], default='N', max_length=1),
        ),
    ]
