# Generated by Django 4.0.6 on 2022-11-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_dictionary_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='classification',
            field=models.CharField(choices=[('Sa', 'Saúde'), ('Ed', 'Educação'), ('Ec', 'Economia'), ('Mo', 'Mobilidade'), ('De', 'Demografia'), ('Me', 'Meio Ambiente'), ('Ur', 'Urbanismo'), ('Se', 'Segurança'), ('Em', 'Empreendedorismo'), ('Te', 'Tecnologia')], default='Ec', max_length=2),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='format',
            field=models.CharField(choices=[('INT', 'Int'), ('FLOAT2', 'Float2'), ('GRAPHIC', 'Graphic'), ('PROGRESS_BAR', 'Progress Bar'), ('STRING', 'String')], default='INT', max_length=12),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='unit',
            field=models.CharField(choices=[('M', 'Money'), ('N', 'Number'), ('D', 'Distance'), ('P', 'Porcentage'), ('K2', 'Square Kilometers'), ('W', 'Wages'), ('H', 'InhabitantKilometers'), ('MB', 'MBPS')], default='N', max_length=2),
        ),
    ]
